### PR TITLE
 Re-review

### PR DESCRIPTION
**Pull request by KirillKotsko**
1.  Add a big ammount of commits, which show the evolution steps of my program.
2.  Add gitignore file.
3.  Improve decomposition of my project: in lab1_list2_v9 operator-  for 2 dates has been divided into 4 small sub-functions, improve code structure(for instance func menu has been replace to demonstration library).
4. Documentation of code optional part for the first laboratory, and I don't added (will add in future update).
5. Add demonstration mode which perform the creation and all functionality of Stack, queue, deque using int, string, vector(lab1_list1) and custom class(lab1_list2) from the second part of the task.

### CODE REVIEW

**Comment by dt-iss** [comment]
1. Decomposition of your project still not correct.
2. Your project is not documented. You should add docummentation strings. See the recommended manuals.
3. You should use inheritance and aggregation for implementation of the class hierarchies in the first and second part of the task.

**Comment by KirillKotsko** [comment]
> 1. Decomposition of your project still not correct.
> 2. Your project is not documented. You should add docummentation strings. See the recommended manuals.
> 3. You should use inheritance and aggregation for implementation of the class hierarchies in the first and second part of the task.

Documentation added + Decomposition of project + add new Classes and replace global fuction(become methods), constants to the classes. 

Ready to re-review.

**Comment by KirillKotsko** [comment]
> 1. Decomposition of your project still not correct.
> 2. Your project is not documented. You should add docummentation strings. See the recommended manuals.
> 3. You should use inheritance and aggregation for implementation of the class hierarchies in the first and second part of the task.
Decomposition of project + improve documantation.

Ready to re-review.

**Comment by KirillKotsko** [comment]
> 1. Decomposition of your project still not correct.
> 2. Your project is not documented. You should add docummentation strings. See the recommended manuals.
> 3. You should use inheritance and aggregation for implementation of the class hierarchies in the first and second part of the task.

Decomposition of project + improve documantation.

**Comment by KirillKotsko** [comment]
> 1. Decomposition of your project still not correct.
> 2. Your project is not documented. You should add docummentation strings. See the recommended manuals.
> 3. You should use inheritance and aggregation for implementation of the class hierarchies in the first and second part of the task.

Mistakes corrected.

**Pull request merged**
